// qwen-loader.js
//
// Loads Qwen3.5-0.8B (a browser-compatible ONNX Vision-Language Model) using
// the real @huggingface/transformers ("Transformers.js") APIs — no invented
// APIs, no mocked model. Runs inside the Qwen Web Worker (qwen-worker.js),
// never on the main/content-script thread.
//
// Model files are NOT downloaded or generated by this code. They are copied
// manually by the developer into:
//   frontend/local-vision/model/Qwen3.5-0.8B-ONNX/
// following the standard multi-file ONNX export layout for Transformers.js
// vision-language models (config.json, tokenizer files, chat_template.jinja,
// and onnx/{embed_tokens,vision_encoder,decoder_model_merged}*.onnx[_data]).
//
// If those files are missing, `loadQwen` simply rejects — there is no
// fallback to a remote/hosted model (env.allowRemoteModels is forced off),
// so a missing local model fails loudly instead of silently phoning home.

import * as Transformers from "@huggingface/transformers";

const { env, AutoProcessor, AutoModelForImageTextToText } = Transformers;

// Must match the folder name under frontend/local-vision/model/.
const MODEL_DIR_NAME = "Qwen3.5-0.8B-ONNX";

// Per-module quantization, matching the exact component files the developer
// will copy in (embed_tokens_q4, vision_encoder_fp16, decoder_model_merged_q4).
// This is Transformers.js's documented "per-module dtypes" feature — see
// https://huggingface.co/docs/transformers.js/guides/dtypes — used the same
// way for every split-ONNX VLM (Florence-2, LLaVA, Qwen2-VL, LFM2-VL, etc.).
const MODEL_DTYPE = {
  embed_tokens: "q4",
  vision_encoder: "fp16",
  decoder_model_merged: "q4",
};

let processor = null;
let model = null;
let device = null;
let loadingPromise = null;
let lastError = null;
let configuredBaseUrl = null;

function configureEnv(modelBaseUrl) {
  if (configuredBaseUrl === modelBaseUrl) return;
  // Never fall back to the Hugging Face Hub. If the local files aren't
  // there, loading must fail — not silently fetch a remote model.
  env.allowRemoteModels = false;
  env.allowLocalModels = true;
  env.useBrowserCache = true;
  // modelBaseUrl is an absolute chrome-extension://<id>/local-vision/model/
  // URL, computed on the main thread (chrome.runtime.getURL is not
  // guaranteed available inside a Worker) and passed in via postMessage.
  env.localModelPath = modelBaseUrl;
  configuredBaseUrl = modelBaseUrl;
}

async function detectDevice() {
  try {
    if (typeof navigator !== "undefined" && navigator.gpu) {
      const adapter = await navigator.gpu.requestAdapter();
      if (adapter) return "webgpu";
    }
  } catch (_err) {
    // fall through to wasm
  }
  return "wasm";
}

/**
 * Loads (once) and returns { model, processor, device }. Safe to call
 * repeatedly/concurrently — subsequent calls reuse the same in-flight or
 * completed load instead of loading Qwen again.
 */
export async function loadQwen(modelBaseUrl, onProgress) {
  if (model && processor) return { model, processor, device };
  if (loadingPromise) return loadingPromise;

  loadingPromise = (async () => {
    if (!modelBaseUrl) {
      throw new Error("Local Vision: missing model base URL.");
    }
    configureEnv(modelBaseUrl);
    device = await detectDevice();

    onProgress?.({ status: "loading-processor", device });
    processor = await AutoProcessor.from_pretrained(MODEL_DIR_NAME, {
      local_files_only: true,
      progress_callback: (p) => onProgress?.({ status: "processor", ...p }),
    });

    // Qwen3.5's architecture (config.json -> "architectures": ["Qwen3_5ForConditionalGeneration"])
    // is natively supported by Transformers.js v4.0+ (see PR #1551, "Add
    // support for new Qwen VL models (Qwen2.5-VL, Qwen3-VL, Qwen3.5, and
    // Qwen3.5 MoE)"), which this project already depends on via
    // @huggingface/transformers ^4.2.0. We use that specific class directly
    // rather than a generic Auto* class so model dispatch can't silently
    // fall through to the wrong architecture. If a given installed version
    // doesn't export it under this name for some reason, we fall back to
    // the generic AutoModelForImageTextToText, which dispatches by
    // config.json's model_type instead.
    const ModelClass = Transformers.Qwen3_5ForConditionalGeneration || AutoModelForImageTextToText;
    const fromPretrained = (opts) => ModelClass.from_pretrained(MODEL_DIR_NAME, opts);

    onProgress?.({ status: "loading-model", device });
    try {
      model = await fromPretrained({
        local_files_only: true,
        device,
        dtype: MODEL_DTYPE,
        progress_callback: (p) => onProgress?.({ status: "model", ...p }),
      });
    } catch (err) {
      if (device === "webgpu") {
        // WebGPU unsupported/unavailable for this model/GPU combo — fail
        // safe by retrying once on WASM rather than failing the whole
        // module outright.
        onProgress?.({ status: "webgpu-failed", error: err?.message });
        device = "wasm";
        model = await fromPretrained({
          local_files_only: true,
          device,
          dtype: MODEL_DTYPE,
          progress_callback: (p) => onProgress?.({ status: "model", ...p }),
        });
      } else {
        throw err;
      }
    }

    onProgress?.({ status: "ready", device });
    return { model, processor, device };
  })();

  loadingPromise = loadingPromise.catch((err) => {
    lastError = err;
    // Allow a later retry (e.g. once the developer copies the model files
    // in) instead of caching a permanent failure.
    loadingPromise = null;
    processor = null;
    model = null;
    throw err;
  });

  return loadingPromise;
}

export function isQwenReady() {
  return !!(model && processor);
}

export function getQwenDevice() {
  return device;
}

export function getQwenLastError() {
  return lastError;
}

export function disposeQwen() {
  try {
    model?.dispose?.();
  } catch (_err) {
    // best-effort cleanup only
  }
  model = null;
  processor = null;
  loadingPromise = null;
  lastError = null;
  configuredBaseUrl = null;
}
